### ISSUE TITLE
Revisão do Livro

### ISSUE THREAD

**Issue by pedro-hos** [jesuino/livros#3]
@jesuino Parabéns cara, o livro está ótimo, com uma leitura agradável, e fluente. Listei algumas melhorias gramaticais que peguei durante a leitura do livro. 

- **Página 9**: 
  - Vocë, explicaÇão, cõdigo
- **Página 13**: 
  - X(imagine	o	posicionamento	como	um plano	cartesiano) => separar x de (....
- **Páginas 15 e 16**: 
  - Aqui	carregamos	o	clipe	de	áudio	e	informamos	a	URL	do	audio	a	ser	tocado;	2/	O => Numeração errada
- **Página 17**: 
  - remoto(carregando => separar remoto de (....
- **Página 18**: 
  - numeração do codigo esta errada o 4 repete 2x
- **Página 20**: 
  - Logos todos => Logo
- **Página 24**:
  - Qualquer componente é passível	de	sobre	ações	desse	tipo	por	parte do usuário => Acho que podemos colocar uma `,` depois de _sobre_
  - o tipo do parämetro
- **Página 28**: 
  - e	indeterminado(você => separar (
- **Página 32**: 
  - MultipleSelectionModel(permite	=> separar (
  - SingleSelectionModel(permite 	=> separar (
- **Página 35**
  - leiaute(ou	layout => separar (
  - vocë	deve	ter	percebido	
- **Página 36**: 
  - Hoje	vamos	mostrar	só	três classes:	VBox ... => acho que a palavra hoje, não cabe aqui
- **Página 44**:
  - se vocề	redimensiona	o	pai => você está com uma acentuação "estranha"
  - centro	para	a	direita,	centro	//	para	esquerda => Trocar ou tirar `//`
- **Página 46**: 
  - opacidade(tranparência) => separar (
  - nó(um	botão, => separar (
- **Página 47**:
  - objeto	Pathpassado;
- **Página 49**:
  - FabricaTransicao.. => 2 pontos finais
- **Página 50**: 
  - abstrata(setAutoReverse => separar (
- **Página 51**:
  - tocando(ou	que	=> separar (
- **Página 67**:
  - .	A	fábrica	você	deve => . na linha de baixo
- **Página 80**:
  - Alguns ( grudados com o texto
- **Página 82**:
  - Você pulou uma linha entre a linha 3 e 4

**Comment by jesuino** [comment]
Ótimas contribuições, agradeço imensamente! Vou fazer hoje e soltar uma versão 1.1!

**Comment by PauloLuan** [comment]
@jesuino era melhor vc postar o source do livro e a gente commita lá direto... conforme #2

**Comment by jesuino** [comment]
Estou arrumando isso, em alguns minutos eu vou apagar esse repo!

--
*William Antônio Siqueira*
*Java Support Engineer*

*http://fxapps.blogspot.com <http://fxapps.blogspot.com>*
*http://www.williamantonio.wordpress.com
<http://www.williamantonio.wordpress.com>*

2016-12-23 14:26 GMT-02:00 Paulo Luan <notifications@github.com>:

**Comment by jesuino** [comment]
Cõdigo movido para -> https://github.com/jesuino/livro-javafx-pratico

Mas vou manter esse repo com os binários!
